export const words: any = {
  Pelajaran1: [
    "aa ss dd ff jj kk ll ;;",
    "dads sfjk d;kf d;ld",
    "kkak ldld afas fkds",
    "ddj; s;kl ;f;l ;dja",
    "jjal lka; jajj dldl",
    "das das asad asad",
    "alf salak dad asal akas sajak",
    "laff sjds ajas fsff",
    "as jala ada lada al kala",
  ],
  Pelajaran2: [
    "qq ww ee rr tt yy uu ii oo pp",
    "eqw ret tiy ypo qwe rty uio",
    "qwe qwe ert rty tyu yui iop",
    "tyut qwert poiuy qweertt yuio",
    "poiuyt trewq qwerty poiuyt",
    "qwert qwert qwert qwert",
    "try tyu iop qwe rty uio",
    "qwerty ytrewq poiuyt qwerty",
    "qwerty trewq poiuyt qwerty",
  ],
  Pelajaran3: [
    "zz xx cc vv bb nn mm ,,, ...",
    "zxc vbn m,. zxcv bnm ,./",
    "zxc zxc vbn vbn m,./ m,./",
    "xvcm zbn,. mv,. czx ,bmn",
    "zxcv bnm,./ zxcv bnm,./",
    "zxcvbnm ,.zxcv ,.bnm,",
    "xcz vbnm ,.xcz vbnm,",
    "zxcvbnm ,.zxcv ,.bnm,",
    "zxcv bnm ,.zxcv bnm,",
  ],

  Pelajaran4: [
    "abac bcab cabc dabc eabc fabc gabc habc",
    "ijkl jklm klmn lmno mnop nopq opqr pqrs",
    "tuvwx uvwxy vwxyz wxyza xyzab yzabc zabcd",
    "defgh efghi fghij ghijk hijkl ijklm jklmn",
    "mnopq nopqr opqrs pqrst qrstu rstuv stuvw",
    "vwxyz wxyza xyzab yzabc zabcd abcde bcdef",
    "rstuv stuvw tuvwxy uvwxyz vwxyza wxyzab",
    "yzabc zabcd abcde bcdef cdefg defgh efghi",
    "ghijk hijkl ijklm jklmn klmno lmno pq",
  ],
  Pelajaran5: [
    "aku dan dia",
    "dia itu baik",
    "buku dan pena",
    "makan nasi ayam",
    "mobil merah baru",
    "kucing tidur",
    "rumah besar",
    "jalan ke pasar",
    "hujan turun deras",
  ],
  Pelajaran6: [
    "saya suka makan",
    "dia pergi ke toko",
    "mobil itu cepat",
    "rumahnya di kota",
    "dia sangat cantik",
    "kucing saya tidur",
    "anak itu pintar",
    "saya baca buku",
    "dia menulis surat",
  ],
  Pelajaran7: [
    "saya makan nasi dan dia minum teh",
    "mobil itu merah dan cepat",
    "dia pergi ke pasar beli sayur",
    "buku ini sangat menarik dan bagus",
    "saya suka membaca dan menulis",
    "rumahnya di kota besar dan indah",
    "dia sangat pintar dan rajin",
    "saya makan roti dan minum susu",
    "kucing itu lucu dan menggemaskan",
  ],
  Pelajaran8: [
    "12 34 56 78 90",
    "1a 2s 3d 4f 5g 6h 7j 8k 9l 0;",
    "q1 w2 e3 r4 t5 y6 u7 i8 o9 p0",
    "1z 2x 3c 4v 5b 6n 7m 8, 9. 0/",
    "1q 2w 3e 4r 5t 6y 7u 8i 9o 0p",
    "q1a 2sw 3de 4fr 5gt 6hy 7uj 8ik 9ol 0p;",
    "1zq 2wx 3ec 4rv 5bt 6yn 7um 8i, 9o. 0p/",
    "q1w 2e 3r 4t 5y 6u 7i 8o 9p",
    "1q 2w 3e 4r 5t 6y 7u 8i 9o 0p",
  ],
  Pelajaran9: [
    "1! 2@ 3# 4$ 5% 6^ 7& 8* 9( 0)",
    "!a @s #d $f %g ^h &j *k (l )",
    "q! w@ e# r$ t% y^ u& i* o( p)",
    "!z @x #c $v %b ^n &m *, (.",
    "!q @w #e $r %t ^y &u *i (o )p",
    "!1@ 2s# 3d$ 4f% 5g^ 6h& 7j* 8k( 9l) 0;",
    "!zq @wx #ec $rv %bt ^yn &um *, (o.",
    "q! w@ e# r$ t% y^ u& i* o( p)",
    "1! 2@ 3# 4$ 5% 6^ 7& 8* 9( 0)",
  ],
  Pelajaran10: [
    "` ~ - _ = +",
    "`a ~s -d _f =g +h",
    "q` w~ e- r_ t= y+",
    "`z ~x -c _v =b +n",
    "`q ~w -e _r =t +y",
    "`1 ~2 -3 _4 =5 +6",
    "1` 2~ 3- 4_ 5= 6+",
    "q` w~ e- r_ t= y+",
    "`q ~w -e _r =t +y",
  ],
};
